/**
 * Local resolution for the stock photography layer.
 *
 * Photographs are supplied by the owner and dropped into
 * `assets/images/stock/`. Nothing is downloaded at build time, so every
 * reference is resolved against the filesystem first: where a photograph is
 * present it is used, and where it is missing the generated SVG illustration
 * stays in place. The build therefore never emits a broken <img>, whether the
 * photo library is complete, partial or entirely empty.
 *
 * The same rule governs every optional rendition — an AVIF sibling or a smaller
 * width variant is only ever referenced once the file exists on disk.
 *
 * See STOCK-IMAGE-DOWNLOADS.md (generated by the build) for the required
 * filenames and their current status.
 */

import { existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');

/** Directory the owner drops downloaded photographs into. */
export const STOCK_DIR = '/assets/images/stock';

/** Master size every stock photograph is prepared at. */
export const PHOTO_WIDTH = 1400;
export const PHOTO_HEIGHT = 900;

/**
 * Optional smaller renditions. `tree-service-arborist-900.webp` next to
 * `tree-service-arborist.webp` is picked up automatically and offered through
 * srcset; nothing breaks when it is absent.
 */
export const VARIANT_WIDTHS = [900];

/** Does a site-root path such as "/assets/images/stock/x.webp" exist on disk? */
export function assetExists(path) {
  if (typeof path !== 'string' || !path.startsWith('/')) return false;
  return existsSync(resolve(ROOT, path.slice(1)));
}

const withExtension = (path, extension) => path.replace(/\.[a-z0-9]+$/i, extension);
const withWidth = (path, width) => path.replace(/(\.[a-z0-9]+)$/i, `-${width}$1`);

/**
 * Every candidate for one encoding of a photograph, widest last, as a srcset
 * string — or null when the base file for that encoding is not present.
 */
function srcsetFor(basePath, extension, width) {
  const base = withExtension(basePath, extension);
  if (!assetExists(base)) return null;

  const smaller = VARIANT_WIDTHS.filter((candidate) => candidate < width)
    .map((candidate) => ({ url: withWidth(base, candidate), width: candidate }))
    .filter((entry) => assetExists(entry.url));

  if (smaller.length === 0) return { src: base, srcset: null };
  return {
    src: base,
    srcset: [...smaller, { url: base, width }].map((entry) => `${entry.url} ${entry.width}w`).join(', '),
  };
}

/**
 * Resolve one industry-style image to whatever is actually available.
 *
 * @param {object} options
 * @param {string} [options.photo]        Site-root path to the stock photograph (.webp)
 * @param {string} [options.photoAlt]     Alt text for the photograph
 * @param {string} options.illustration   Site-root path to the SVG fallback
 * @param {string} options.illustrationAlt
 * @param {string} [options.sizes]        `sizes` hint, only used when a srcset is emitted
 * @returns {{isPhoto: boolean, src: string, alt: string, width: number, height: number,
 *            srcset: string|null, sources: {type: string, srcset: string}[], sizes: string|null}}
 */
export function resolveImage({
  photo = null,
  photoAlt = '',
  illustration,
  illustrationAlt,
  photoWidth = PHOTO_WIDTH,
  photoHeight = PHOTO_HEIGHT,
  illustrationWidth = 800,
  illustrationHeight = 560,
  sizes = null,
}) {
  const webp = photo ? srcsetFor(photo, '.webp', photoWidth) : null;

  if (!webp) {
    return {
      isPhoto: false,
      src: illustration,
      alt: illustrationAlt,
      width: illustrationWidth,
      height: illustrationHeight,
      srcset: null,
      sources: [],
      sizes: null,
    };
  }

  const avif = srcsetFor(photo, '.avif', photoWidth);
  return {
    isPhoto: true,
    src: webp.src,
    alt: photoAlt,
    width: photoWidth,
    height: photoHeight,
    srcset: webp.srcset,
    // Only AVIF needs a <source>; the <img> already carries the WebP candidates.
    sources: avif ? [{ type: 'image/avif', srcset: avif.srcset ?? avif.src }] : [],
    sizes: webp.srcset || avif?.srcset ? sizes : null,
  };
}

/** Resolve the artwork for one industry, photograph first, illustration second. */
export function industryImage(industry, { sizes = null } = {}) {
  return resolveImage({
    photo: industry.stockImage,
    photoAlt: industry.stockImageAlt,
    illustration: industry.art,
    illustrationAlt: industry.artAlt,
    sizes,
  });
}

/** True when the industry's photograph has been downloaded. */
export function hasIndustryPhoto(industry) {
  return Boolean(industry.stockImage) && assetExists(withExtension(industry.stockImage, '.webp'));
}
