/**
 * Local resolution for the stock photography layer.
 *
 * Photographs are supplied by the owner and dropped into
 * `assets/images/stock/`. Nothing is downloaded at build time, so every
 * reference is resolved against the filesystem first: where a photograph is
 * present it is used, and where it is missing the generated SVG illustration
 * stays in place. The build therefore never emits a broken <img>, whether the
 * photo library is complete, partial or entirely empty.
 *
 * The same rule governs every optional rendition — an AVIF sibling or a smaller
 * width variant is only ever referenced once the file exists on disk.
 *
 * See STOCK-IMAGE-DOWNLOADS.md (generated by the build) for the required
 * filenames and their current status.
 */

import { existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');

/** Directory the owner drops downloaded photographs into. */
export const STOCK_DIR = '/assets/images/stock';

/** Master size every stock photograph is prepared at. */
export const PHOTO_WIDTH = 1400;
export const PHOTO_HEIGHT = 900;

/**
 * Optional smaller renditions. `tree-service-arborist-900.webp` next to
 * `tree-service-arborist.webp` is picked up automatically and offered through
 * srcset; nothing breaks when it is absent.
 */
export const VARIANT_WIDTHS = [900];

/**
 * Accepted formats for the base file, best first.
 *
 * The data declares `.webp` because that is what the site should ship, but a
 * JPEG or PNG saved straight out of the download is accepted at the same name.
 * That way the photograph appears the moment the file is dropped in, and
 * converting to WebP stays an optimisation rather than a precondition.
 */
export const BASE_FORMATS = ['.webp', '.jpg', '.jpeg', '.png'];

/**
 * Is this an externally hosted image rather than a path into the repository?
 *
 * Remote URLs skip the filesystem layer entirely: there is no file to stat, no
 * sibling rendition to discover and no extension to swap, so `baseFile()`,
 * `withExtension()`, `assetExists()` and `srcsetFor()` are never given one.
 */
export function isRemoteImage(value) {
  return typeof value === 'string' && /^https?:\/\//i.test(value);
}

/** Does a site-root path such as "/assets/images/stock/x.webp" exist on disk? */
export function assetExists(path) {
  if (typeof path !== 'string' || !path.startsWith('/')) return false;
  return existsSync(resolve(ROOT, path.slice(1)));
}

const withExtension = (path, extension) => path.replace(/\.[a-z0-9]+$/i, extension);
const withWidth = (path, width) => path.replace(/(\.[a-z0-9]+)$/i, `-${width}$1`);

/** The base file actually on disk for a declared photo path, in any accepted format. */
export function baseFile(photo) {
  if (!photo) return null;
  return BASE_FORMATS.map((extension) => withExtension(photo, extension)).find(assetExists) ?? null;
}

/**
 * Width-descriptor srcset for one encoding, widest last — or null when no
 * smaller rendition exists, in which case a plain `src` says it all.
 */
function srcsetFor(base, width) {
  const smaller = VARIANT_WIDTHS.filter((candidate) => candidate < width)
    .map((candidate) => ({ url: withWidth(base, candidate), width: candidate }))
    .filter((entry) => assetExists(entry.url));

  if (smaller.length === 0) return null;
  return [...smaller, { url: base, width }].map((entry) => `${entry.url} ${entry.width}w`).join(', ');
}

/**
 * Resolve one industry-style image to whatever is actually available.
 *
 * @param {object} options
 * @param {string} [options.photo]        Site-root path to the stock photograph (.webp)
 * @param {string} [options.photoAlt]     Alt text for the photograph
 * @param {string} options.illustration   Site-root path to the SVG fallback
 * @param {string} options.illustrationAlt
 * @param {string} [options.sizes]        `sizes` hint, only used when a srcset is emitted
 * @returns {{isPhoto: boolean, src: string, alt: string, width: number, height: number,
 *            srcset: string|null, sources: {type: string, srcset: string}[], sizes: string|null}}
 */
export function resolveImage({
  photo = null,
  photoAlt = '',
  illustration,
  illustrationAlt,
  photoWidth = PHOTO_WIDTH,
  photoHeight = PHOTO_HEIGHT,
  illustrationWidth = 800,
  illustrationHeight = 560,
  sizes = null,
  objectPosition = null,
}) {
  // A remote photograph is taken at its word — the CDN serves it at the crop
  // the URL asks for, so there is nothing on disk to resolve against.
  if (isRemoteImage(photo)) {
    return {
      isPhoto: true,
      src: photo,
      alt: photoAlt,
      width: photoWidth,
      height: photoHeight,
      srcset: null,
      sources: [],
      sizes: null,
      objectPosition,
    };
  }

  const base = baseFile(photo);

  if (!base) {
    return {
      isPhoto: false,
      src: illustration,
      alt: illustrationAlt,
      width: illustrationWidth,
      height: illustrationHeight,
      srcset: null,
      sources: [],
      sizes: null,
    };
  }

  const avif = withExtension(photo, '.avif');
  const hasAvif = assetExists(avif);
  return {
    isPhoto: true,
    src: base,
    alt: photoAlt,
    width: photoWidth,
    height: photoHeight,
    srcset: srcsetFor(base, photoWidth),
    // Only AVIF needs a <source>; the <img> already carries the base candidates.
    sources: hasAvif ? [{ type: 'image/avif', srcset: srcsetFor(avif, photoWidth) ?? avif }] : [],
    // `picture()` drops this wherever there are no width descriptors to size.
    sizes,
    objectPosition,
  };
}

/**
 * Resolve the artwork for one industry, photograph first, illustration second.
 *
 * `photoPosition` only travels with the photograph: the illustrations are drawn
 * to fit their frame, so shifting their focal point would be meaningless.
 */
export function industryImage(industry, { sizes = null } = {}) {
  return resolveImage({
    photo: industry.stockImage,
    photoAlt: industry.stockImageAlt,
    illustration: industry.art,
    illustrationAlt: industry.artAlt,
    objectPosition: industry.photoPosition ?? null,
    sizes,
  });
}

/** True when the industry has a photograph — downloaded locally or hosted remotely. */
export function hasIndustryPhoto(industry) {
  return isRemoteImage(industry.stockImage) || baseFile(industry.stockImage) !== null;
}
