/**
 * Generates STOCK-IMAGE-DOWNLOADS.md — the record of every stock photograph the
 * site is wired up for, where it comes from, and whether the file has been
 * downloaded yet.
 *
 * It is generated rather than hand-maintained so the "present / missing" column
 * cannot drift from what is actually on disk: drop a file into
 * assets/images/stock/, run `npm run build`, and the table updates itself.
 *
 * The source URLs live here and in src/data/industries.mjs only. They are never
 * rendered on the website — they exist so the owner can find each photograph
 * again and confirm its licence.
 */

import { industries } from './data/industries.mjs';
import { assetExists, PHOTO_WIDTH, PHOTO_HEIGHT, STOCK_DIR, VARIANT_WIDTHS } from './lib/media.mjs';

/** Where each industry's photograph appears once it exists. */
const USAGE = {
  'tree-service-websites': [
    'Homepage industry card (featured)',
    'Industries hub — hero mosaic tile 1 and industry card',
    'Tree service website-design page — hero',
    'Home services hub — hero',
  ],
  'concrete-contractor-websites': [
    'Homepage industry card (featured)',
    'Industries hub — hero mosaic tile 2 and industry card',
    'Concrete contractor website page — hero',
  ],
  'fence-company-websites': [
    'Homepage industry card (featured)',
    'Industries hub — hero mosaic tile 3 and industry card',
    'Fence company website page — hero',
  ],
  'landscaping-websites': [
    'Homepage industry card (featured)',
    'Industries hub — hero mosaic tile 4 and industry card',
    'Landscaping website page — hero',
  ],
  'pool-service-websites': ['Industries hub — industry card', 'Pool service website page — hero'],
  'garage-door-websites': ['Industries hub — industry card', 'Garage door website page — hero'],
  'roofing-websites': ['Industries hub — industry card', 'Roofing website page — hero'],
  'outdoor-services-websites': ['Industries hub — industry card', 'Outdoor services website page — hero'],
  'real-estate-websites': ['Industries hub — industry card', 'Real estate website page — hero'],
  'attorney-websites': ['Industries hub — industry card', 'Attorney website page — hero'],
};

/** Crop guidance for the person preparing each file. */
const FRAMING = {
  'tree-service-websites': 'Keep the arborist, the lift and the tree in frame; do not crop the subject out behind text.',
  'concrete-contractor-websites':
    'Keep the crew and the fresh pour visible. This is the flagship image — concrete contractors are the primary target market.',
  'fence-company-websites': 'Show both the installers and the fence structure clearly.',
  'landscaping-websites': 'Keep the worker and the mower in frame alongside the finished lawn.',
  'pool-service-websites': 'Favour the service professional over a crop that shows only the water.',
  'garage-door-websites': 'Landscape crop emphasising the garage doors and the residential exterior.',
  'roofing-websites': 'Keep the worker, safety equipment, shingles and roof structure visible.',
  'outdoor-services-websites': 'Show both the worker and a recognisable house exterior.',
  'real-estate-websites': 'An active property consultation — not a generic handshake crop.',
  'attorney-websites': 'Keep the whole consultation scene rather than cropping tightly to one person.',
};

const status = (path) => (assetExists(path) ? 'present' : 'missing');

function entry(industry) {
  const webp = industry.stockImage;
  const avif = webp.replace(/\.webp$/, '.avif');
  const present = assetExists(webp);
  const file = webp.replace(`${STOCK_DIR}/`, '');

  return `### ${industry.name}

| Field | Value |
| --- | --- |
| Status | **${present ? 'present' : 'MISSING — the SVG illustration is being used instead'}** |
| Source page | <${industry.stockSourceUrl}> |
| Required file | \`assets/images/stock/${file}\` |
| Prepare at | ${PHOTO_WIDTH} × ${PHOTO_HEIGHT} px (14:9), WebP quality 78–82, under ~300 KB |
| Alt text | ${industry.stockImageAlt} |
| Fallback illustration | \`${industry.art.replace('/assets/images/art/', 'assets/images/art/')}\` |
| Optional AVIF | \`${avif.replace(`${STOCK_DIR}/`, 'assets/images/stock/')}\` — ${status(avif)} |
| Optional ${VARIANT_WIDTHS.join('/')} px variant | \`${file.replace(/\.webp$/, `-${VARIANT_WIDTHS[0]}.webp`)}\` — ${status(webp.replace(/\.webp$/, `-${VARIANT_WIDTHS[0]}.webp`))} |

Framing: ${FRAMING[industry.slug]}

Used on:

${USAGE[industry.slug].map((place) => `- ${place}`).join('\n')}
`;
}

export function buildStockRecord() {
  const withPhotos = industries.filter((industry) => industry.stockImage);
  const present = withPhotos.filter((industry) => assetExists(industry.stockImage));
  const missing = withPhotos.filter((industry) => !assetExists(industry.stockImage));

  return `<!-- Generated by \`npm run build\` (src/stock-record.mjs). Edits will be overwritten. -->

# Stock image downloads

Design Rank Studio uses photographs of real service work for its industry
imagery. **This repository does not download them** — the build has no network
access and stock photo hosts are blocked by the environment's egress policy, so
the files below have to be downloaded by hand.

Nothing breaks while they are missing. Every reference is resolved against the
filesystem at build time by \`resolveImage()\` in \`src/lib/media.mjs\`: where a
photograph exists it is used, and where it does not the generated SVG
illustration stays in place. Add files whenever you like and re-run
\`npm run build\`.

**Status: ${present.length} of ${withPhotos.length} photographs present, ${missing.length} still missing.**

## How to add a photograph

1. Open the source page listed for the image below.
2. **Check the licence and the download conditions on the page at the time you
   download.** Unsplash and Pexels licences are permissive but they do change,
   individual photographers can add restrictions, and some images carry
   model or property release limits that matter for commercial marketing use.
   Confirm the terms before you publish, and keep a note of what they were.
3. Download the largest version offered.
4. Crop to the framing note, resize to ${PHOTO_WIDTH} × ${PHOTO_HEIGHT} and export as WebP at
   quality 78–82. Squoosh (squoosh.app), \`cwebp\` or any image editor will do:

   \`\`\`bash
   cwebp -q 80 -resize ${PHOTO_WIDTH} 0 source.jpg -o assets/images/stock/<name>.webp
   \`\`\`

5. Save it at the exact filename listed — the build looks for that name.
6. Run \`npm run build && npm run check\`.

### Optional extras

Both are picked up automatically when present and ignored when absent, so
neither is required:

- **AVIF** — an \`.avif\` sibling of the same name is offered ahead of the WebP
  through \`<picture>\`, typically 20–30% smaller again.
- **A ${VARIANT_WIDTHS.join('/')} px variant** — \`<name>-${VARIANT_WIDTHS[0]}.webp\` (${VARIANT_WIDTHS[0]} × 600, under ~180 KB) is
  added to the \`srcset\` so card and mosaic slots do not download the full-size
  hero file. Worth doing for the four featured industries at least.

The source URLs below are a record for you. They are never rendered on the site
and are not used as image sources.

## Images

${withPhotos.map((industry) => entry(industry)).join('\n')}
## Not replaced

These stay as illustrations on purpose:

- \`hero-composition.svg\`, \`before-after.svg\`, \`review-findings.svg\`,
  \`industries-overview.svg\` and the five \`service-*.svg\` files — they explain
  website structure, rankings, analytics and conversion, which a photograph
  cannot do.
- \`about-remote.svg\` — the About page. A stock portrait must not stand in for
  the founder. See \`docs/CONTENT-NEEDED.md\` item 4.
- Portfolio thumbnails, the logo, the favicon, the OG preview and every
  interface icon.
`;
}
